spring:
  profiles:
    active: local,log
  jmx:
    enabled: false
  aop:
    proxy-target-class: true

# Security 설정
security:
  oauth2:
    # OAuth 서버 Client 정보
    client:
      client-id: registry
      client-secret: registry-secret
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
    auth-server-uri: http://localhost:8080

# LOG 설정
logging:
  config: classpath:logback.xml

# WAS 설정
server:
  port: 8080

---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Local Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: local

  # DB
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/registry?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: registry
    password: registry1234$$
    max-active: 10
    max-idle: 10
    min-idle: 10
    initial-size: 10
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    max-wait: 1000
    validation-query: SELECT 1
  jpa:
    database: mysql
    show-sql: false
    hibernate:
#      ddl-auto: create
#      ddl-auto: update
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        hbm2ddl:
          import_files: /sql/init.sql

# Config
config:
---
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# Log Profile
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
spring:
  profiles: log
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# LOG 설정
logging:
  config: classpath:logback-console.xml
---